# Generated by Django 4.0.1 on 2022-02-27 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('images', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('description', models.TextField()),
                ('slug', models.SlugField(null=True)),
            ],
        ),
    ]
