# Generated by Django 4.0.1 on 2022-03-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total', models.PositiveIntegerField(blank=True)),
                ('total_price', models.PositiveIntegerField(blank=True)),
                ('activate', models.BooleanField(default=True)),
                ('cars', models.ManyToManyField(to='cars.Cars')),
            ],
        ),
    ]
