# Generated by Django 4.0.1 on 2022-02-09 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='actif',
            field=models.BooleanField(),
        ),
    ]
