# Generated by Django 4.0.1 on 2022-02-09 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_products_actif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='actif',
            field=models.BooleanField(default=True),
        ),
    ]
